# Generated by Django 5.1.6 on 2026-03-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('cta_text', models.CharField(default='Shop Now', max_length=60)),
                ('target_url', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='promotions/')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('open_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'position'], name='core_promot_is_acti_036321_idx'), models.Index(fields=['starts_at', 'ends_at'], name='core_promot_starts__e93836_idx')],
            },
        ),
    ]
